
import { ISyllables, ToneSandhiSyllable, Syllables } from './syllable'
import { letters, AlphabeticLetter } from './metadata'

// Zitt 字 beh lih burzs 連音形

//------------------------------------------------------------------------------
//  Allomorphemic Syllables
//------------------------------------------------------------------------------

export class AllomorphemicSyllables extends Syllables {
    list: Array<ToneSandhiSyllable>;


    get length() {
        return this.list.length;
    }

    constructor() {
        super();
        this.list = new Array();
        for(let key in allomorphemic_syllables_with_tone_mark.list) {
            this.list.push(allomorphemic_syllables_with_tone_mark.list[key])
        }
    }

    match(letters: Array<AlphabeticLetter>) {
        return super.match(letters);
    }
}

export let allomorphemic_syllables_with_tone_mark: ISyllables = {
    list: {
        a: new ToneSandhiSyllable([letters.list['a']]),
        ay: new ToneSandhiSyllable([letters.list['a'], letters.list['y']]),
        azs: new ToneSandhiSyllable([letters.list['a'], letters.list['zs']]),
        ah: new ToneSandhiSyllable([letters.list['a'], letters.list['h']]),
        af: new ToneSandhiSyllable([letters.list['a'], letters.list['f']]),
        ai: new ToneSandhiSyllable([letters.list['a'], letters.list['i']]),
        aiy: new ToneSandhiSyllable([letters.list['a'], letters.list['i'], letters.list['y']]),
        aiw: new ToneSandhiSyllable([letters.list['a'], letters.list['i'], letters.list['w']]),
        ainnzs: new ToneSandhiSyllable([letters.list['a'], letters.list['i'], letters.list['nn'], letters.list['zs']]),
        ak: new ToneSandhiSyllable([letters.list['a'], letters.list['k']]),
        am: new ToneSandhiSyllable([letters.list['a'], letters.list['m']]),
        amy: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['y']]),
        amw: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['w']]),
        amx: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['x']]),
        amzs: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['zs']]),
        an: new ToneSandhiSyllable([letters.list['a'], letters.list['n']]),
        any: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['y']]),
        anw: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['w']]),
        anx: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['x']]),
        anzs: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['zs']]),
        ang: new ToneSandhiSyllable([letters.list['a'], letters.list['ng']]),
        angw: new ToneSandhiSyllable([letters.list['a'], letters.list['ng'], letters.list['w']]),
        angx: new ToneSandhiSyllable([letters.list['a'], letters.list['ng'], letters.list['x']]),
        angzs: new ToneSandhiSyllable([letters.list['a'], letters.list['ng'], letters.list['zs']]),
        annw: new ToneSandhiSyllable([letters.list['a'], letters.list['nn'], letters.list['w']]),
        annx: new ToneSandhiSyllable([letters.list['a'], letters.list['nn'], letters.list['x']]),
        annzs: new ToneSandhiSyllable([letters.list['a'], letters.list['nn'], letters.list['zs']]),
        ap: new ToneSandhiSyllable([letters.list['a'], letters.list['p']]),
        ab: new ToneSandhiSyllable([letters.list['a'], letters.list['b']]),
        at: new ToneSandhiSyllable([letters.list['a'], letters.list['t']]),
        au: new ToneSandhiSyllable([letters.list['a'], letters.list['u']]),
        auy: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['y']]),
        auw: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['w']]),
        aux: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['x']]),
        auzs: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['zs']]),

        ba: new ToneSandhiSyllable([letters.list['b'], letters.list['a']]),
        bax: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['x']]),
        bazs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['zs']]),
        bah: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['h']]),
        bai: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['i']]),
        baiy: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['i'], letters.list['y']]),
        baix: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['i'], letters.list['x']]),
        bak: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['k']]),
        bag: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['g']]),
        ban: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n']]),
        bany: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n'], letters.list['y']]),
        banx: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n'], letters.list['x']]),
        banzs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        bangy: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['y']]),
        bangw: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['w']]),
        bangx: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['x']]),
        bangzs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        bat: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['t']]),
        bad: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['d']]),
        bauy: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['u'], letters.list['y']]),
        bauzs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['u'], letters.list['zs']]),
        bey: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['y']]),
        bex: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['x']]),
        bezs: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['zs']]),
        beh: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['h']]),
        bef: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['f']]),
        biy: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['y']]),
        bix: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['x']]),
        bizs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['zs']]),
        bieny: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['y']]),
        bienx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['x']]),
        bienzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['zs']]),
        bied: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['d']]),
        biauy: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['y']]),
        biaux: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['x']]),
        biauzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['zs']]),
        bih: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['h']]),
        bif: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['f']]),
        big: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['g']]),
        biny: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['n'], letters.list['y']]),
        binx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['n'], letters.list['x']]),
        binzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['n'], letters.list['zs']]),
        bingy: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ng'], letters.list['y']]),
        bingx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ng'], letters.list['x']]),
        bingzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ng'], letters.list['zs']]),
        biury: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ur'], letters.list['y']]),
        biurx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ur'], letters.list['x']]),
        biurzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ur'], letters.list['zs']]),
        bit: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['t']]),
        biuzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['u'], letters.list['zs']]),
        bury: new ToneSandhiSyllable([letters.list['b'], letters.list['ur'], letters.list['y']]),
        burx: new ToneSandhiSyllable([letters.list['b'], letters.list['ur'], letters.list['x']]),
        burzs: new ToneSandhiSyllable([letters.list['b'], letters.list['ur'], letters.list['zs']]),
        bok: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['k']]),
        bog: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['g']]),
        bong: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng']]),
        bongy: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['y']]),
        bongw: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['w']]),
        bongx: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['x']]),
        bongzs: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['zs']]),
        boy: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['y']]),
        box: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['x']]),
        bozs: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['zs']]),
        buy: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['y']]),
        bux: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['x']]),
        buzs: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['zs']]),
        buax: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['x']]),
        buah: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['h']]),
        buaf: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['f']]),
        buany: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['y']]),
        buad: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['d']]),
        buey: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['e'], letters.list['y']]),
        buex: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['e'], letters.list['x']]),
        buezs: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['e'], letters.list['zs']]),
        buef: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['d'], letters.list['f']]),
        bui: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['i']]),
        buny: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['y']]),
        bunw: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['w']]),
        bunx: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['x']]),
        bunzs: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['zs']]),
        but: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['t']]),
        bud: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['d']]),

        e: new ToneSandhiSyllable([letters.list['e']]),
        ey: new ToneSandhiSyllable([letters.list['e'], letters.list['y']]),
        ew: new ToneSandhiSyllable([letters.list['e'], letters.list['w']]),
        ex: new ToneSandhiSyllable([letters.list['e'], letters.list['x']]),
        ezs: new ToneSandhiSyllable([letters.list['e'], letters.list['zs']]),
        eh: new ToneSandhiSyllable([letters.list['e'], letters.list['h']]),
        ef: new ToneSandhiSyllable([letters.list['e'], letters.list['f']]),
        enn: new ToneSandhiSyllable([letters.list['e'], letters.list['nn']]),
        ennx: new ToneSandhiSyllable([letters.list['e'], letters.list['nn'], letters.list['x']]),

        gax: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['x']]),
        gazs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['zs']]),
        gaix: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['i'], letters.list['x']]),
        gaizs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['i'], letters.list['zs']]),
        gag: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['g']]),
        gamy: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['m'], letters.list['y']]),
        gamx: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['m'], letters.list['x']]),
        gamzs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['m'], letters.list['zs']]),
        gany: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['y']]),
        ganw: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['w']]),
        ganx: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['x']]),
        ganzs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        gangzs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        gaux: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['u'], letters.list['x']]),
        gew: new ToneSandhiSyllable([letters.list['g'], letters.list['e'], letters.list['w']]),
        gex: new ToneSandhiSyllable([letters.list['g'], letters.list['e'], letters.list['x']]),
        gezs: new ToneSandhiSyllable([letters.list['g'], letters.list['e'], letters.list['zs']]),
        giy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['y']]),
        gix: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['x']]),
        gizs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['zs']]),
        giax: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['x'], letters.list['a']]),
        giah: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['h']]),
        giaf: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['f']]),
        giamy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['y']]),
        giamx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['x']]),
        giamzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['zs']]),
        gieny: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['y']]),
        gienw: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['w']]),
        gienx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['x']]),
        gienzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['zs']]),
        giang: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['ng']]),
        giangw: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['ng'], letters.list['w']]),
        giangzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        giap: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['p']]),
        giab: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['b']]),
        giet: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['t']]),
        gied: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['d']]),
        giaux: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['x']]),
        gig: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['g']]),
        gimy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['m'], letters.list['y']]),
        gimx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['m'], letters.list['x']]),
        gimzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['m'], letters.list['zs']]),
        giny: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['n'], letters.list['y']]),
        ginx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['n'], letters.list['x']]),
        ginzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['n'], letters.list['zs']]),
        gingy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ng'], letters.list['y']]),
        gingx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ng'], letters.list['x']]),
        giury: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ur'], letters.list['y']]),
        giurx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ur'], letters.list['x']]),
        giurf: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ur'], letters.list['f']]),
        giok: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['o'], letters.list['k']]),
        giog: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['o'], letters.list['g']]),
        giongy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['y']]),
        giuy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['u'], letters.list['y']]),
        giux: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['u'], letters.list['x']]),
        gurx: new ToneSandhiSyllable([letters.list['g'], letters.list['ur'], letters.list['x']]),
        gurzs: new ToneSandhiSyllable([letters.list['g'], letters.list['ur'], letters.list['zs']]),
        gog: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['g']]),
        gongx: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['ng'], letters.list['x']]),
        gongzs: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['ng'], letters.list['zs']]),
        gox: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['x']]),
        gozs: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['zs']]),
        guy: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['y']]),
        gux: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['x']]),
        guzs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['zs']]),
        guay: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['y']]),
        guazs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['zs']]),
        guany: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['y']]),
        guanx: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['x']]),
        guanzs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        guad: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['d']]),
        guezs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['e'], letters.list['zs']]),
        guef: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['e'], letters.list['f']]),
        guix: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['i'], letters.list['x']]),
        guizs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['i'], letters.list['zs']]),
        





        diurf: new ToneSandhiSyllable([letters.list['d'], letters.list['i'], letters.list['ur'], letters.list['f']]),
    }
}