
import { ISyllables, ToneSandhiSyllable, Syllables } from './syllable'
import { letters, AlphabeticLetter } from './metadata'

// Zitt 字 beh lih burzs 連音形

//------------------------------------------------------------------------------
//  Allomorphemic Syllables
//------------------------------------------------------------------------------

export class AllomorphemicSyllables extends Syllables {
    list: Array<ToneSandhiSyllable>;


    get length() {
        return this.list.length;
    }

    constructor() {
        super();
        this.list = new Array();
        for(let key in allomorphemic_syllables_with_tone_mark.list) {
            this.list.push(allomorphemic_syllables_with_tone_mark.list[key])
        }
    }

    match(letters: Array<AlphabeticLetter>) {
        return super.match(letters);
    }
}

export let allomorphemic_syllables_with_tone_mark: ISyllables = {
    list: {
        a: new ToneSandhiSyllable([letters.list['a']]),
        ay: new ToneSandhiSyllable([letters.list['a'], letters.list['y']]),
        azs: new ToneSandhiSyllable([letters.list['a'], letters.list['zs']]),
        ah: new ToneSandhiSyllable([letters.list['a'], letters.list['h']]),
        af: new ToneSandhiSyllable([letters.list['a'], letters.list['f']]),
        ai: new ToneSandhiSyllable([letters.list['a'], letters.list['i']]),
        aiy: new ToneSandhiSyllable([letters.list['a'], letters.list['i'], letters.list['y']]),
        aiw: new ToneSandhiSyllable([letters.list['a'], letters.list['i'], letters.list['w']]),
        ainnzs: new ToneSandhiSyllable([letters.list['a'], letters.list['i'], letters.list['nn'], letters.list['zs']]),
        ak: new ToneSandhiSyllable([letters.list['a'], letters.list['k']]),
        am: new ToneSandhiSyllable([letters.list['a'], letters.list['m']]),
        amy: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['y']]),
        amw: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['w']]),
        amx: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['x']]),
        amzs: new ToneSandhiSyllable([letters.list['a'], letters.list['m'], letters.list['zs']]),
        an: new ToneSandhiSyllable([letters.list['a'], letters.list['n']]),
        any: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['y']]),
        anw: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['w']]),
        anx: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['x']]),
        anzs: new ToneSandhiSyllable([letters.list['a'], letters.list['n'], letters.list['zs']]),
        ang: new ToneSandhiSyllable([letters.list['a'], letters.list['ng']]),
        angw: new ToneSandhiSyllable([letters.list['a'], letters.list['ng'], letters.list['w']]),
        angx: new ToneSandhiSyllable([letters.list['a'], letters.list['ng'], letters.list['x']]),
        angzs: new ToneSandhiSyllable([letters.list['a'], letters.list['ng'], letters.list['zs']]),
        annw: new ToneSandhiSyllable([letters.list['a'], letters.list['nn'], letters.list['w']]),
        annx: new ToneSandhiSyllable([letters.list['a'], letters.list['nn'], letters.list['x']]),
        annzs: new ToneSandhiSyllable([letters.list['a'], letters.list['nn'], letters.list['zs']]),
        ap: new ToneSandhiSyllable([letters.list['a'], letters.list['p']]),
        ab: new ToneSandhiSyllable([letters.list['a'], letters.list['b']]),
        at: new ToneSandhiSyllable([letters.list['a'], letters.list['t']]),
        au: new ToneSandhiSyllable([letters.list['a'], letters.list['u']]),
        auy: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['y']]),
        auw: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['w']]),
        aux: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['x']]),
        auzs: new ToneSandhiSyllable([letters.list['a'], letters.list['u'], letters.list['zs']]),

        ba: new ToneSandhiSyllable([letters.list['b'], letters.list['a']]),
        bax: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['x']]),
        bazs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['zs']]),
        bah: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['h']]),
        bai: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['i']]),
        baiy: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['i'], letters.list['y']]),
        baix: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['i'], letters.list['x']]),
        bak: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['k']]),
        bag: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['g']]),
        ban: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n']]),
        bany: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n'], letters.list['y']]),
        banx: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n'], letters.list['x']]),
        banzs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        bangy: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['y']]),
        bangw: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['w']]),
        bangx: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['x']]),
        bangzs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        bat: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['t']]),
        bad: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['d']]),
        bauy: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['u'], letters.list['y']]),
        bauzs: new ToneSandhiSyllable([letters.list['b'], letters.list['a'], letters.list['u'], letters.list['zs']]),
        bey: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['y']]),
        bex: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['x']]),
        bezs: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['zs']]),
        beh: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['h']]),
        bef: new ToneSandhiSyllable([letters.list['b'], letters.list['e'], letters.list['f']]),
        biy: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['y']]),
        bix: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['x']]),
        bizs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['zs']]),
        bieny: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['y']]),
        bienx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['x']]),
        bienzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['zs']]),
        bied: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['e'], letters.list['d']]),
        biauy: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['y']]),
        biaux: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['x']]),
        biauzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['zs']]),
        bih: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['h']]),
        bif: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['f']]),
        big: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['g']]),
        biny: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['n'], letters.list['y']]),
        binx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['n'], letters.list['x']]),
        binzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['n'], letters.list['zs']]),
        bingy: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ng'], letters.list['y']]),
        bingx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ng'], letters.list['x']]),
        bingzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ng'], letters.list['zs']]),
        biury: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ur'], letters.list['y']]),
        biurx: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ur'], letters.list['x']]),
        biurzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['ur'], letters.list['zs']]),
        bit: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['t']]),
        biuzs: new ToneSandhiSyllable([letters.list['b'], letters.list['i'], letters.list['u'], letters.list['zs']]),
        bury: new ToneSandhiSyllable([letters.list['b'], letters.list['ur'], letters.list['y']]),
        burx: new ToneSandhiSyllable([letters.list['b'], letters.list['ur'], letters.list['x']]),
        burzs: new ToneSandhiSyllable([letters.list['b'], letters.list['ur'], letters.list['zs']]),
        bok: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['k']]),
        bog: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['g']]),
        bong: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng']]),
        bongy: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['y']]),
        bongw: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['w']]),
        bongx: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['x']]),
        bongzs: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['ng'], letters.list['zs']]),
        boy: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['y']]),
        box: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['x']]),
        bozs: new ToneSandhiSyllable([letters.list['b'], letters.list['o'], letters.list['zs']]),
        buy: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['y']]),
        bux: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['x']]),
        buzs: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['zs']]),
        buax: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['x']]),
        buah: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['h']]),
        buaf: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['f']]),
        buany: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['y']]),
        buad: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['a'], letters.list['d']]),
        buey: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['e'], letters.list['y']]),
        buex: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['e'], letters.list['x']]),
        buezs: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['e'], letters.list['zs']]),
        buef: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['d'], letters.list['f']]),
        bui: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['i']]),
        buny: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['y']]),
        bunw: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['w']]),
        bunx: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['x']]),
        bunzs: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['n'], letters.list['zs']]),
        but: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['t']]),
        bud: new ToneSandhiSyllable([letters.list['b'], letters.list['u'], letters.list['d']]),

        diurf: new ToneSandhiSyllable([letters.list['d'], letters.list['i'], letters.list['ur'], letters.list['f']]),

        e: new ToneSandhiSyllable([letters.list['e']]),
        ey: new ToneSandhiSyllable([letters.list['e'], letters.list['y']]),
        ew: new ToneSandhiSyllable([letters.list['e'], letters.list['w']]),
        ex: new ToneSandhiSyllable([letters.list['e'], letters.list['x']]),
        ezs: new ToneSandhiSyllable([letters.list['e'], letters.list['zs']]),
        eh: new ToneSandhiSyllable([letters.list['e'], letters.list['h']]),
        ef: new ToneSandhiSyllable([letters.list['e'], letters.list['f']]),
        enn: new ToneSandhiSyllable([letters.list['e'], letters.list['nn']]),
        ennx: new ToneSandhiSyllable([letters.list['e'], letters.list['nn'], letters.list['x']]),

        gax: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['x']]),
        gazs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['zs']]),
        gaix: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['i'], letters.list['x']]),
        gaizs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['i'], letters.list['zs']]),
        gag: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['g']]),
        gamy: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['m'], letters.list['y']]),
        gamx: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['m'], letters.list['x']]),
        gamzs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['m'], letters.list['zs']]),
        gany: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['y']]),
        ganw: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['w']]),
        ganx: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['x']]),
        ganzs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        gangzs: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        gaux: new ToneSandhiSyllable([letters.list['g'], letters.list['a'], letters.list['u'], letters.list['x']]),
        gew: new ToneSandhiSyllable([letters.list['g'], letters.list['e'], letters.list['w']]),
        gex: new ToneSandhiSyllable([letters.list['g'], letters.list['e'], letters.list['x']]),
        gezs: new ToneSandhiSyllable([letters.list['g'], letters.list['e'], letters.list['zs']]),
        giy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['y']]),
        gix: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['x']]),
        gizs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['zs']]),
        giax: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['x'], letters.list['a']]),
        giah: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['h']]),
        giaf: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['f']]),
        giamy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['y']]),
        giamx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['x']]),
        giamzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['zs']]),
        gieny: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['y']]),
        gienw: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['w']]),
        gienx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['x']]),
        gienzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['zs']]),
        giang: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['ng']]),
        giangw: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['ng'], letters.list['w']]),
        giangzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        giap: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['p']]),
        giab: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['b']]),
        giet: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['t']]),
        gied: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['e'], letters.list['d']]),
        giaux: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['x']]),
        gig: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['g']]),
        gimy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['m'], letters.list['y']]),
        gimx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['m'], letters.list['x']]),
        gimzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['m'], letters.list['zs']]),
        giny: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['n'], letters.list['y']]),
        ginx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['n'], letters.list['x']]),
        ginzs: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['n'], letters.list['zs']]),
        gingy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ng'], letters.list['y']]),
        gingx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ng'], letters.list['x']]),
        giury: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ur'], letters.list['y']]),
        giurx: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ur'], letters.list['x']]),
        giurf: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['ur'], letters.list['f']]),
        giok: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['o'], letters.list['k']]),
        giog: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['o'], letters.list['g']]),
        giongy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['y']]),
        giuy: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['u'], letters.list['y']]),
        giux: new ToneSandhiSyllable([letters.list['g'], letters.list['i'], letters.list['u'], letters.list['x']]),
        gurx: new ToneSandhiSyllable([letters.list['g'], letters.list['ur'], letters.list['x']]),
        gurzs: new ToneSandhiSyllable([letters.list['g'], letters.list['ur'], letters.list['zs']]),
        gog: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['g']]),
        gongx: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['ng'], letters.list['x']]),
        gongzs: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['ng'], letters.list['zs']]),
        gox: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['x']]),
        gozs: new ToneSandhiSyllable([letters.list['g'], letters.list['o'], letters.list['zs']]),
        guy: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['y']]),
        gux: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['x']]),
        guzs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['zs']]),
        guay: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['y']]),
        guazs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['zs']]),
        guany: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['y']]),
        guanx: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['x']]),
        guanzs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        guad: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['a'], letters.list['d']]),
        guezs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['e'], letters.list['zs']]),
        guef: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['e'], letters.list['f']]),
        guix: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['i'], letters.list['x']]),
        guizs: new ToneSandhiSyllable([letters.list['g'], letters.list['u'], letters.list['i'], letters.list['zs']]),
        
        ha: new ToneSandhiSyllable([letters.list['h'], letters.list['a']]),
        haw: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['w']]),
        hax: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['x']]),
        hazs: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['zs']]),
        hah: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['h']]),
        haf: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['f']]),
        hai: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['i']]),
        haiy: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['i'], letters.list['y']]),
        haix: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['i'], letters.list['x']]),
        haizs: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['i'], letters.list['zs']]),
        hainn: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['i'], letters.list['nn']]),
        hainnw: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['i'], letters.list['nn'], letters.list['w']]),
        hainnx: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['i'], letters.list['nn'], letters.list['x']]),
        hak: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['k']]),
        hag: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['g']]),
        ham: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['m']]),
        hamy: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['m'], letters.list['y']]),
        hamw: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['m'], letters.list['w']]),
        hamx: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['m'], letters.list['x']]),
        hamzs: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['m'], letters.list['zs']]),
        han: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['n']]),
        hany: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['n'], letters.list['y']]),
        hanw: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['n'], letters.list['w']]),
        hanx: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['n'], letters.list['x']]),
        hanzs: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        hang: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['ng']]),
        hangw: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['ng'], letters.list['w']]),
        hangx: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['ng'], letters.list['x']]),
        hangzs: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        hanny: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['nn'], letters.list['y']]),
        hannx: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['nn'], letters.list['x']]),
        hannzs: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['nn'], letters.list['zs']]),
        hannh: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['nn'], letters.list['h']]),
        hap: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['p']]),
        hab: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['b']]),
        hat: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['t']]),
        had: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['d']]),
        hau: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['u']]),
        hauy: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['u'], letters.list['y']]),
        hauw: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['u'], letters.list['w']]),
        haux: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['u'], letters.list['x']]),
        hauzs: new ToneSandhiSyllable([letters.list['h'], letters.list['a'], letters.list['u'], letters.list['zs']]),
        he: new ToneSandhiSyllable([letters.list['h'], letters.list['e']]),
        hey: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['y']]),
        hew: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['w']]),
        hex: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['x']]),
        hezs: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['zs']]),
        heh: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['h']]),
        hennw: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['nn'], letters.list['w']]),
        hennx: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['nn'], letters.list['x']]),
        hennh: new ToneSandhiSyllable([letters.list['h'], letters.list['e'], letters.list['nn'], letters.list['h']]),
        hi: new ToneSandhiSyllable([letters.list['h'], letters.list['i']]),
        hiy: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['y']]),
        hiw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['w']]),
        hix: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['x']]),
        hia: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a']]),
        hiazs: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['zs']]),
        hiah: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['h']]),
        hiaf: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['f']]),
        hiam: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['m']]),
        hiamy: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['y']]),
        hiamw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['w']]),
        hiamx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['m'], letters.list['x']]),
        hien: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['e'], letters.list['n']]),
        hieny: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['y']]),
        hienw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['w']]),
        hienx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['x']]),
        hienzs: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['e'], letters.list['n'], letters.list['zs']]),
        hiang: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['ng']]),
        hiangy: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['ng'], letters.list['y']]),
        hiangw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['ng'], letters.list['w']]),
        hiann: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['nn']]),
        hianny: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['y']]),
        hiannw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['w']]),
        hiannx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['x']]),
        hiannzs: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['zs']]),
        hiannh: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['h']]),
        hiab: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['b']]),
        hiat: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['t']]),
        hiad: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['d']]),
        hiau: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['u']]),
        hiauy: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['y']]),
        hiaux: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['x']]),
        hiauh: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['a'], letters.list['u'], letters.list['h']]),
        hik: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['k']]),
        hig: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['g']]),
        him: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['m']]),
        himx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['m'], letters.list['x']]),
        hin: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['n']]),
        hinx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['n'], letters.list['x']]),
        hinzs: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['n'], letters.list['zs']]),
        hing: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ng']]),
        hingw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ng'], letters.list['w']]),
        hingx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ng'], letters.list['x']]),
        hingzs: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ng'], letters.list['zs']]),
        hinn: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['nn']]),
        hinnw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['nn'], letters.list['w']]),
        hinnzs: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['nn'], letters.list['zs']]),
        hiurx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ur'], letters.list['x']]),
        hiurzs: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ur'], letters.list['zs']]),
        hiurh: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ur'], letters.list['h']]),
        hiurf: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['ur'], letters.list['f']]),
        hiok: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['o'], letters.list['k']]),
        hiong: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['o'], letters.list['ng']]),
        hiongy: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['y']]),
        hiongw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['w']]),
        hiongx: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['x']]),
        hip: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['p']]),
        hit: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['t']]),
        hid: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['d']]),
        hiu: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['u']]),
        hiuy: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['u'], letters.list['y']]),
        hiuw: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['u'], letters.list['w']]),
        hiux: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['u'], letters.list['x']]),
        hiunn: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['u'], letters.list['nn']]),
        hiunnf: new ToneSandhiSyllable([letters.list['h'], letters.list['i'], letters.list['u'], letters.list['nn'], letters.list['f']]),
        hmy: new ToneSandhiSyllable([letters.list['h'], letters.list['m'], letters.list['y']]),
        hmx: new ToneSandhiSyllable([letters.list['h'], letters.list['m'], letters.list['x']]),
        hmh: new ToneSandhiSyllable([letters.list['h'], letters.list['m'], letters.list['h']]),
        hmf: new ToneSandhiSyllable([letters.list['h'], letters.list['m'], letters.list['f']]),
        hng: new ToneSandhiSyllable([letters.list['h'], letters.list['ng']]),
        hngy: new ToneSandhiSyllable([letters.list['h'], letters.list['ng'], letters.list['y']]),
        hngx: new ToneSandhiSyllable([letters.list['h'], letters.list['ng'], letters.list['x']]),
        hngzs: new ToneSandhiSyllable([letters.list['h'], letters.list['ng'], letters.list['zs']]),
        hngh: new ToneSandhiSyllable([letters.list['h'], letters.list['ng'], letters.list['h']]),
        hngf: new ToneSandhiSyllable([letters.list['h'], letters.list['ng'], letters.list['f']]),
        hury: new ToneSandhiSyllable([letters.list['h'], letters.list['ur'], letters.list['y']]),
        hurx: new ToneSandhiSyllable([letters.list['h'], letters.list['ur'], letters.list['x']]),
        hurzs: new ToneSandhiSyllable([letters.list['h'], letters.list['ur'], letters.list['zs']]),
        hurf: new ToneSandhiSyllable([letters.list['h'], letters.list['ur'], letters.list['f']]),
        hok: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['k']]),
        hog: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['g']]),
        hong: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['ng']]),
        hongy: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['ng'], letters.list['y']]),
        hongw: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['ng'], letters.list['w']]),
        hongx: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['ng'], letters.list['x']]),
        hongzs: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['ng'], letters.list['zs']]),
        honn: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['nn']]),
        honny: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['nn'], letters.list['y']]),
        honnw: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['nn'], letters.list['w']]),
        honnh: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['nn'], letters.list['h']]),
        ho: new ToneSandhiSyllable([letters.list['h'], letters.list['o']]),
        hoy: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['y']]),
        how: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['w']]),
        hox: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['x']]),
        hozs: new ToneSandhiSyllable([letters.list['h'], letters.list['o'], letters.list['zs']]),
        hu: new ToneSandhiSyllable([letters.list['h'], letters.list['u']]),
        huy: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['y']]),
        huw: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['w']]),
        hux: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['x']]),
        huzs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['zs']]),
        hua: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a']]),
        huaw: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['w']]),
        huax: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['x']]),
        huazs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['zs']]),
        huah: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['h']]),
        huaf: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['f']]),
        huaix: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['i'], letters.list['x']]),
        huaizs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['i'], letters.list['zs']]),
        huainnx: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['i'], letters.list['nn'], letters.list['x']]),
        huan: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['n']]),
        huany: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['y']]),
        huanw: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['w']]),
        huanx: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['x']]),
        huanzs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['n'], letters.list['zs']]),
        huann: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['nn']]),
        huanny: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['nn'], letters.list['y']]),
        huannx: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['nn'], letters.list['x']]),
        huannzs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['nn'], letters.list['zs']]),
        huat: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['t']]),
        huad: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['a'], letters.list['d']]),
        hue: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['e']]),
        huey: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['e'], letters.list['y']]),
        huew: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['e'], letters.list['w']]),
        huex: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['e'], letters.list['x']]),
        huezs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['e'], letters.list['zs']]),
        hueh: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['e'], letters.list['h']]),
        hui: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['i']]),
        huiy: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['i'], letters.list['y']]),
        huiw: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['i'], letters.list['w']]),
        huix: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['i'], letters.list['x']]),
        huizs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['i'], letters.list['zs']]),
        hun: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['n']]),
        huny: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['n'], letters.list['y']]),
        hunw: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['n'], letters.list['w']]),
        hunx: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['n'], letters.list['x']]),
        hunzs: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['n'], letters.list['zs']]),
        hut: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['t']]),
        hud: new ToneSandhiSyllable([letters.list['h'], letters.list['u'], letters.list['d']]),

        i: new ToneSandhiSyllable([letters.list['i']]),
        iy: new ToneSandhiSyllable([letters.list['i'], letters.list['y']]),
        iw: new ToneSandhiSyllable([letters.list['i'], letters.list['w']]),
        ix: new ToneSandhiSyllable([letters.list['i'], letters.list['x']]),
        izs: new ToneSandhiSyllable([letters.list['i'], letters.list['zs']]),
        ia: new ToneSandhiSyllable([letters.list['i'], letters.list['a']]),
        iay: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['y']]),
        iaw: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['w']]),
        iax: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['x']]),
        iazs: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['zs']]),
        iah: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['h']]),
        iaf: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['f']]),
        iam: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['m']]),
        iamy: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['m'], letters.list['y']]),
        iamx: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['m'], letters.list['x']]),
        iamzs: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['m'], letters.list['zs']]),
        ien: new ToneSandhiSyllable([letters.list['i'], letters.list['e'], letters.list['n']]),
        ieny: new ToneSandhiSyllable([letters.list['i'], letters.list['e'], letters.list['n'], letters.list['y']]),
        ienw: new ToneSandhiSyllable([letters.list['i'], letters.list['e'], letters.list['n'], letters.list['w']]),
        ienx: new ToneSandhiSyllable([letters.list['i'], letters.list['e'], letters.list['n'], letters.list['x']]),
        iang: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['ng']]),
        iangzs: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['ng'], letters.list['zs']]),
        iann: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['nn']]),
        ianny: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['y']]),
        iannw: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['w']]),
        iannx: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['x']]),
        iannzs: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['nn'], letters.list['zs']]),
        iap: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['p']]),
        iab: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['b']]),
        iat: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['t']]),
        iad: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['d']]),
        iau: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['u']]),
        iauy: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['u'], letters.list['y']]),
        iauw: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['u'], letters.list['w']]),
        iaux: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['u'], letters.list['x']]),
        iauzs: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['u'], letters.list['zs']]),
        iaunn: new ToneSandhiSyllable([letters.list['i'], letters.list['a'], letters.list['u'], letters.list['nn']]),
        ik: new ToneSandhiSyllable([letters.list['i'], letters.list['k']]),
        ig: new ToneSandhiSyllable([letters.list['i'], letters.list['g']]),
        im: new ToneSandhiSyllable([letters.list['i'], letters.list['m']]),
        imy: new ToneSandhiSyllable([letters.list['i'], letters.list['m'], letters.list['y']]),
        imw: new ToneSandhiSyllable([letters.list['i'], letters.list['m'], letters.list['w']]),
        imx: new ToneSandhiSyllable([letters.list['i'], letters.list['m'], letters.list['x']]),
        in: new ToneSandhiSyllable([letters.list['i'], letters.list['n']]),
        iny: new ToneSandhiSyllable([letters.list['i'], letters.list['n'], letters.list['y']]),
        inw: new ToneSandhiSyllable([letters.list['i'], letters.list['n'], letters.list['w']]),
        inx: new ToneSandhiSyllable([letters.list['i'], letters.list['n'], letters.list['x']]),
        inzs: new ToneSandhiSyllable([letters.list['i'], letters.list['n'], letters.list['zs']]),
        ing: new ToneSandhiSyllable([letters.list['i'], letters.list['ng']]),
        ingy: new ToneSandhiSyllable([letters.list['i'], letters.list['ng'], letters.list['y']]),
        ingw: new ToneSandhiSyllable([letters.list['i'], letters.list['ng'], letters.list['w']]),
        ingx: new ToneSandhiSyllable([letters.list['i'], letters.list['ng'], letters.list['x']]),
        ingzs: new ToneSandhiSyllable([letters.list['i'], letters.list['ng'], letters.list['zs']]),
        inn: new ToneSandhiSyllable([letters.list['i'], letters.list['nn']]),
        inny: new ToneSandhiSyllable([letters.list['i'], letters.list['nn'], letters.list['y']]),
        innw: new ToneSandhiSyllable([letters.list['i'], letters.list['nn'], letters.list['w']]),
        innx: new ToneSandhiSyllable([letters.list['i'], letters.list['nn'], letters.list['x']]),
        innzs: new ToneSandhiSyllable([letters.list['i'], letters.list['nn'], letters.list['zs']]),
        iur: new ToneSandhiSyllable([letters.list['i'], letters.list['ur']]),
        iury: new ToneSandhiSyllable([letters.list['i'], letters.list['ur'], letters.list['y']]),
        iurx: new ToneSandhiSyllable([letters.list['i'], letters.list['ur'], letters.list['x']]),
        iurh: new ToneSandhiSyllable([letters.list['i'], letters.list['ur'], letters.list['h']]),
        iurf: new ToneSandhiSyllable([letters.list['i'], letters.list['ur'], letters.list['f']]),
        iok: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['k']]),
        iog: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['g']]),
        iong: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['ng']]),
        iongy: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['y']]),
        iongw: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['w']]),
        iongx: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['x']]),
        iongzs: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['ng'], letters.list['zs']]),
        ip: new ToneSandhiSyllable([letters.list['i'], letters.list['p']]),
        it: new ToneSandhiSyllable([letters.list['i'], letters.list['t']]),
        id: new ToneSandhiSyllable([letters.list['i'], letters.list['d']]),
        iu: new ToneSandhiSyllable([letters.list['i'], letters.list['u']]),
        iuy: new ToneSandhiSyllable([letters.list['i'], letters.list['u'], letters.list['y']]),
        iuw: new ToneSandhiSyllable([letters.list['i'], letters.list['u'], letters.list['w']]),
        iux: new ToneSandhiSyllable([letters.list['i'], letters.list['u'], letters.list['x']]),
        iuzs: new ToneSandhiSyllable([letters.list['i'], letters.list['u'], letters.list['zs']]),
        iunn: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['nn']]),
        iunny: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['nn'], letters.list['y']]),
        iunnx: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['nn'], letters.list['x']]),
        iunnzs: new ToneSandhiSyllable([letters.list['i'], letters.list['o'], letters.list['nn'], letters.list['zs']]),

        jiy: new ToneSandhiSyllable([letters.list['j'], letters.list['i'], letters.list['y']]),
        jix: new ToneSandhiSyllable([letters.list['j'], letters.list['i'], letters.list['x']]),
        jizs: new ToneSandhiSyllable([letters.list['j'], letters.list['i'], letters.list['zs']]),
        jia: new ToneSandhiSyllable([letters.list['j'], letters.list['i'], letters.list['a']]),
        jiay: new ToneSandhiSyllable([letters.list['j'], letters.list['i'], letters.list['a'], letters.list['y']]),



    }
}