

interface Lexicon {
    readonly [index: string]: Array<string>
}


export let lexicon: Lexicon = {
    a: ['阿', '鴉'],
    af: [],
    ah: [],
    aiy: [],
    aiw: [],
    ainnzs: [],
    ay: ['仔'],
    aw: [],
    azs: ['阿'],
    ang: ['尫'],
    angx: ['紅'],
    angzs: ['紅'],
    baggziu: ['目珠'],
    bah: ['肉'],
    baiy: ['醜'],
    bax: ['貓'],
    beh: ['卜'],
    behh: ['卜'],
    buaxqiny: [],
    bueh: [],
    burx: ['無'],
    burzs: ['無'], 
    canzscauy: ['canzs 草'],
    cenn: ['青'],
    cezs: ['尋'],
    cinn: ['青'],
    cienzscauy: ['cienzs 草'],
    cuazs: ['𤆬'],
    cuaih: [],
    cuddkih: [],
    cuddlaih: [],
    cuezs: ['尋'],
    cuiw: ['嘴'],
    da: ['焦', '乾'],
    dak: ['大'],
    damy: ['店'],
    damwvurfxuay: [],
    damwvurfxua: [],
    diamy: ['店'],
    diurf: ['着'],
    diurh: [],
    diurhh: [],
    dit: [],
    dngy: ['返'],
    dngffkih: [],
    dngfflaih: [],
    durh: [],
    e: [],
    ezs: ['能'],
    ew: [],
    ex: ['个', '兮'],
    gaux: ['賢'],
    giax: ['夯'],
    giny: ['囝'],
    ginssnassqianny: [],
    gua: [],
    guaw: [],
    guay: [],
    guazs: [],
    gun: ['阮'],
    gunw: ['阮'],
    guny: ['阮'],
    gunzs: ['阮'],
    hua: ['吪'],
    huang: ['風'],
    he: [],
    hitt: [],
    i: [],
    iw: [],
    inw: [],
    izs: [],
    iaw: [],
    in: [],
    inzs: [],
    jibbkih: [],
    jibbbaih: [],
    ka: ['脚'],
    kahh: [],
    kaih: [],
    keh: ['䀫'],
    ki: [],
    kiazs: ['豎'],
    kiffkih: [],
    kifflih: [],
    kifflaih: [],
    kihhlaizs: [],
    kih: [],
    kihh: [],
    ko: ['圓'],
    ku: [],
    kuainnw: [],
    kuany: ['欵'],
    kunw: ['困'],
    kuannymaixiay: [],
    kuannymaizs: [],
    kuh: [],
    kueh: ['䀫'],
    kuhh: [],
    kuih: [],
    laih: [],
    laizs: [],
    lamx: ['湳'],
    lan: ['咱'],
    lanw: ['咱'],
    lany: [],
    lanzs: ['咱', '玍'],
    langh: [],
    le: [],
    leh: [],
    lehh: [],
    lih: [],
    lit: [],
    li: [],
    liw: [],
    liy: [],
    lizs: [],
    lim: [],
    lin: [],
    linw: [],
    liny: [],
    linzs: [],
    luaih: [],
    lueh: [],
    lurffkih: [],
    lurfflaih: [],
    mw: ['不'],
    maizs: ['覓'],
    mih: ['乜'],
    nazs: ['若'],
    naw: ['若'],
    o: ['烏', '黑'],
    pah: ['打'],
    pangzs: ['隙'],
    painny: ['歹', '呆'],
    piet: ['丿'],
    pongw: ['凸'],
    qah: ['恰'],
    qahh: [],
    qahy: [],
    qam: [],
    qannzs: [],
    qausszanycah: ['九層 cah'],
    qaux: ['猿'],
    qianny: ['子'],
    queh: [],
    quefflaih: [],
    puah: [],
    nassqahy: [],
    siauw: ['賬', '數'],
    simssmi: [],
    sih: [],
    suaw: ['續'],
    taix: ['刣'],
    tiannw: ['痛'],
    urygiurx: [],
    uw: [],
    vuttlissia: [],
    vuttzissia: [],
    zaizsianny: ['知', '知 ianny'],
    zausszing: ['走真'],
    zeh: [],
    ziddleh: [],
    zi: [],
    zia: ['者'],
    ze: [],
    zit: [],
    zitt: [],
    zuannzs: ['濺'],
    zuezs: ['多'],
    zury: [],
    zunzs: ['拵'],
  };
